spring.application.name=insureflow-backend

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/insureflow
spring.datasource.username=postgres
spring.datasource.password=tanay

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SERVER CONFIGURATION
server.port=8080

# DEVTOOLS
spring.devtools.restart.enabled=true

#JWT CONFIGURATION
jwt.secret=insureflowsecuritysecureinsureflowsecuritysecureinsureflowsecuritysecure
jwt.expiration=86400000